In [91]:
import numpy as np
import pandas as pd
np.set_printoptions(suppress=True)

Version of NumPy *

In [4]:
np.__version__

'1.16.2'

Version of Pandas *

In [5]:
pd.__version__

'0.24.2'

In [6]:
data1 =  pd.read_csv('~/Downloads/data.csv')

In [14]:
data1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11914 entries, 0 to 11913
Data columns (total 16 columns):
Make                 11914 non-null object
Model                11914 non-null object
Year                 11914 non-null int64
Engine Fuel Type     11911 non-null object
Engine HP            11845 non-null float64
Engine Cylinders     11884 non-null float64
Transmission Type    11914 non-null object
Driven_Wheels        11914 non-null object
Number of Doors      11908 non-null float64
Market Category      8172 non-null object
Vehicle Size         11914 non-null object
Vehicle Style        11914 non-null object
highway MPG          11914 non-null int64
city mpg             11914 non-null int64
Popularity           11914 non-null int64
MSRP                 11914 non-null int64
dtypes: float64(3), int64(5), object(8)
memory usage: 1.5+ MB


In [15]:
data1['Make'].unique()

array(['BMW', 'Audi', 'FIAT', 'Mercedes-Benz', 'Chrysler', 'Nissan',
       'Volvo', 'Mazda', 'Mitsubishi', 'Ferrari', 'Alfa Romeo', 'Toyota',
       'McLaren', 'Maybach', 'Pontiac', 'Porsche', 'Saab', 'GMC',
       'Hyundai', 'Plymouth', 'Honda', 'Oldsmobile', 'Suzuki', 'Ford',
       'Cadillac', 'Kia', 'Bentley', 'Chevrolet', 'Dodge', 'Lamborghini',
       'Lincoln', 'Subaru', 'Volkswagen', 'Spyker', 'Buick', 'Acura',
       'Rolls-Royce', 'Maserati', 'Lexus', 'Aston Martin', 'Land Rover',
       'Lotus', 'Infiniti', 'Scion', 'Genesis', 'HUMMER', 'Tesla',
       'Bugatti'], dtype=object)

In [18]:
data1[data1['Make']=='BMW'].info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 334 entries, 0 to 11905
Data columns (total 16 columns):
Make                 334 non-null object
Model                334 non-null object
Year                 334 non-null int64
Engine Fuel Type     334 non-null object
Engine HP            334 non-null float64
Engine Cylinders     334 non-null float64
Transmission Type    334 non-null object
Driven_Wheels        334 non-null object
Number of Doors      334 non-null float64
Market Category      334 non-null object
Vehicle Size         334 non-null object
Vehicle Style        334 non-null object
highway MPG          334 non-null int64
city mpg             334 non-null int64
Popularity           334 non-null int64
MSRP                 334 non-null int64
dtypes: float64(3), int64(5), object(8)
memory usage: 44.4+ KB


In [19]:
np.average(data1[data1['Make']=='BMW']['MSRP'])

61546.76347305389

In [40]:
d = data1[data1['Year']>=2015]['Engine HP'].fillna(np.round(data1[data1['Year']>=2015]['Engine HP'].mean()))

In [39]:
np.round(data1[data1['Year']>=2015]['Engine HP'].isna().sum())

51

In [43]:
np.mean(d)

272.9878231859883

In [44]:
data1[data1['Year']>=2015]['Engine HP'].mean()

272.98771870794076

In [47]:
data2 = data1[data1['Make']=='Rolls-Royce']

In [51]:
data3 = data2[['Engine HP','Engine Cylinders','highway MPG']]

In [56]:
data4 = data3.drop_duplicates()

In [59]:
data5 = data4.to_numpy()

In [62]:
data5.T

array([[325., 563., 563., 563., 322., 453., 624.],
       [  8.,  12.,  12.,  12.,  12.,  12.,  12.],
       [ 15.,  19.,  21.,  20.,  15.,  19.,  21.]])

In [63]:
data5

array([[325.,   8.,  15.],
       [563.,  12.,  19.],
       [563.,  12.,  21.],
       [563.,  12.,  20.],
       [322.,  12.,  15.],
       [453.,  12.,  19.],
       [624.,  12.,  21.]])

In [64]:
XTX =  np.matmul(data5.T,data5)

In [70]:
np.sum(np.flip(XTX))

1970887.0

In [72]:
y =[1000, 1100, 900, 1200, 1000, 850, 1300]

In [73]:
np.flip(XTX)

array([[2.454000e+03, 1.500000e+03, 6.519600e+04],
       [1.500000e+03, 9.280000e+02, 3.965600e+04],
       [6.519600e+04, 3.965600e+04, 1.754801e+06]])

In [87]:
w = np.matmul(np.matmul(np.flip(XTX),data5.T),y)

In [84]:
np.shape(np.matmul(np.flip(XTX),data5.T))

(3, 7)

In [86]:
np.shape(y)

(7,)

In [95]:
np.set_printoptions(suppress=True)
w

array([1.80189129e+10, 1.09881986e+10, 4.81815113e+11])